// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade.proto

package org.yourkoder.com.dataformat;

public final class BinanceTrade {
  private BinanceTrade() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_binancetrade_Trade_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_binancetrade_Trade_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_binancetrade_Trade_List_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_binancetrade_Trade_List_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013trade.proto\022\014binancetrade\"S\n\005Trade\022\n\n\002" +
      "id\030\001 \001(\003\022\016\n\006symbol\030\002 \001(\t\022\014\n\004time\030\003 \001(\t\022\021" +
      "\n\ttimeStamp\030\004 \001(\020\022\r\n\005price\030\005 \001(\001\"4\n\nTrad" +
      "e_List\022&\n\ttradelist\030\001 \003(\0132\023.binancetrade" +
      ".TradeB#\n\021org.yourkoder.comB\014BinanceTrad" +
      "eP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_binancetrade_Trade_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_binancetrade_Trade_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_binancetrade_Trade_descriptor,
        new java.lang.String[] { "Id", "Symbol", "Time", "TimeStamp", "Price", });
    internal_static_binancetrade_Trade_List_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_binancetrade_Trade_List_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_binancetrade_Trade_List_descriptor,
        new java.lang.String[] { "Tradelist", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
