// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade.proto

package org.yourkoder.com.dataformat;

/**
 * Protobuf type {@code binancetrade.Trade_List}
 */
public final class Trade_List extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:binancetrade.Trade_List)
    Trade_ListOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Trade_List.newBuilder() to construct.
  private Trade_List(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Trade_List() {
    tradelist_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Trade_List();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Trade_List(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) != 0)) {
              tradelist_ = new java.util.ArrayList<Trade>();
              mutable_bitField0_ |= 0x00000001;
            }
            tradelist_.add(
                input.readMessage(Trade.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) != 0)) {
        tradelist_ = java.util.Collections.unmodifiableList(tradelist_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return BinanceTrade.internal_static_binancetrade_Trade_List_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return BinanceTrade.internal_static_binancetrade_Trade_List_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Trade_List.class, Trade_List.Builder.class);
  }

  public static final int TRADELIST_FIELD_NUMBER = 1;
  private java.util.List<Trade> tradelist_;
  /**
   * <code>repeated .binancetrade.Trade tradelist = 1;</code>
   */
  @java.lang.Override
  public java.util.List<Trade> getTradelistList() {
    return tradelist_;
  }
  /**
   * <code>repeated .binancetrade.Trade tradelist = 1;</code>
   */
  @java.lang.Override
  public java.util.List<? extends TradeOrBuilder>
      getTradelistOrBuilderList() {
    return tradelist_;
  }
  /**
   * <code>repeated .binancetrade.Trade tradelist = 1;</code>
   */
  @java.lang.Override
  public int getTradelistCount() {
    return tradelist_.size();
  }
  /**
   * <code>repeated .binancetrade.Trade tradelist = 1;</code>
   */
  @java.lang.Override
  public Trade getTradelist(int index) {
    return tradelist_.get(index);
  }
  /**
   * <code>repeated .binancetrade.Trade tradelist = 1;</code>
   */
  @java.lang.Override
  public TradeOrBuilder getTradelistOrBuilder(
      int index) {
    return tradelist_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < tradelist_.size(); i++) {
      output.writeMessage(1, tradelist_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < tradelist_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, tradelist_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Trade_List)) {
      return super.equals(obj);
    }
    Trade_List other = (Trade_List) obj;

    if (!getTradelistList()
        .equals(other.getTradelistList())) return false;
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getTradelistCount() > 0) {
      hash = (37 * hash) + TRADELIST_FIELD_NUMBER;
      hash = (53 * hash) + getTradelistList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Trade_List parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Trade_List parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Trade_List parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Trade_List parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Trade_List parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Trade_List parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Trade_List parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Trade_List parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Trade_List parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Trade_List parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Trade_List parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Trade_List parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Trade_List prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code binancetrade.Trade_List}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:binancetrade.Trade_List)
          Trade_ListOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return BinanceTrade.internal_static_binancetrade_Trade_List_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return BinanceTrade.internal_static_binancetrade_Trade_List_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Trade_List.class, Trade_List.Builder.class);
    }

    // Construct using org.yourkoder.com.Trade_List.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getTradelistFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (tradelistBuilder_ == null) {
        tradelist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        tradelistBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return BinanceTrade.internal_static_binancetrade_Trade_List_descriptor;
    }

    @java.lang.Override
    public Trade_List getDefaultInstanceForType() {
      return Trade_List.getDefaultInstance();
    }

    @java.lang.Override
    public Trade_List build() {
      Trade_List result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Trade_List buildPartial() {
      Trade_List result = new Trade_List(this);
      int from_bitField0_ = bitField0_;
      if (tradelistBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          tradelist_ = java.util.Collections.unmodifiableList(tradelist_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.tradelist_ = tradelist_;
      } else {
        result.tradelist_ = tradelistBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Trade_List) {
        return mergeFrom((Trade_List)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Trade_List other) {
      if (other == Trade_List.getDefaultInstance()) return this;
      if (tradelistBuilder_ == null) {
        if (!other.tradelist_.isEmpty()) {
          if (tradelist_.isEmpty()) {
            tradelist_ = other.tradelist_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureTradelistIsMutable();
            tradelist_.addAll(other.tradelist_);
          }
          onChanged();
        }
      } else {
        if (!other.tradelist_.isEmpty()) {
          if (tradelistBuilder_.isEmpty()) {
            tradelistBuilder_.dispose();
            tradelistBuilder_ = null;
            tradelist_ = other.tradelist_;
            bitField0_ = (bitField0_ & ~0x00000001);
            tradelistBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getTradelistFieldBuilder() : null;
          } else {
            tradelistBuilder_.addAllMessages(other.tradelist_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Trade_List parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Trade_List) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<Trade> tradelist_ =
      java.util.Collections.emptyList();
    private void ensureTradelistIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        tradelist_ = new java.util.ArrayList<Trade>(tradelist_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
            Trade, Trade.Builder, TradeOrBuilder> tradelistBuilder_;

    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public java.util.List<Trade> getTradelistList() {
      if (tradelistBuilder_ == null) {
        return java.util.Collections.unmodifiableList(tradelist_);
      } else {
        return tradelistBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public int getTradelistCount() {
      if (tradelistBuilder_ == null) {
        return tradelist_.size();
      } else {
        return tradelistBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Trade getTradelist(int index) {
      if (tradelistBuilder_ == null) {
        return tradelist_.get(index);
      } else {
        return tradelistBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Builder setTradelist(
        int index, Trade value) {
      if (tradelistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradelistIsMutable();
        tradelist_.set(index, value);
        onChanged();
      } else {
        tradelistBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Builder setTradelist(
        int index, Trade.Builder builderForValue) {
      if (tradelistBuilder_ == null) {
        ensureTradelistIsMutable();
        tradelist_.set(index, builderForValue.build());
        onChanged();
      } else {
        tradelistBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Builder addTradelist(Trade value) {
      if (tradelistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradelistIsMutable();
        tradelist_.add(value);
        onChanged();
      } else {
        tradelistBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Builder addTradelist(
        int index, Trade value) {
      if (tradelistBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureTradelistIsMutable();
        tradelist_.add(index, value);
        onChanged();
      } else {
        tradelistBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Builder addTradelist(
        Trade.Builder builderForValue) {
      if (tradelistBuilder_ == null) {
        ensureTradelistIsMutable();
        tradelist_.add(builderForValue.build());
        onChanged();
      } else {
        tradelistBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Builder addTradelist(
        int index, Trade.Builder builderForValue) {
      if (tradelistBuilder_ == null) {
        ensureTradelistIsMutable();
        tradelist_.add(index, builderForValue.build());
        onChanged();
      } else {
        tradelistBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Builder addAllTradelist(
        java.lang.Iterable<? extends Trade> values) {
      if (tradelistBuilder_ == null) {
        ensureTradelistIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, tradelist_);
        onChanged();
      } else {
        tradelistBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Builder clearTradelist() {
      if (tradelistBuilder_ == null) {
        tradelist_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        tradelistBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Builder removeTradelist(int index) {
      if (tradelistBuilder_ == null) {
        ensureTradelistIsMutable();
        tradelist_.remove(index);
        onChanged();
      } else {
        tradelistBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Trade.Builder getTradelistBuilder(
        int index) {
      return getTradelistFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public TradeOrBuilder getTradelistOrBuilder(
        int index) {
      if (tradelistBuilder_ == null) {
        return tradelist_.get(index);  } else {
        return tradelistBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public java.util.List<? extends TradeOrBuilder>
         getTradelistOrBuilderList() {
      if (tradelistBuilder_ != null) {
        return tradelistBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(tradelist_);
      }
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Trade.Builder addTradelistBuilder() {
      return getTradelistFieldBuilder().addBuilder(
          Trade.getDefaultInstance());
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public Trade.Builder addTradelistBuilder(
        int index) {
      return getTradelistFieldBuilder().addBuilder(
          index, Trade.getDefaultInstance());
    }
    /**
     * <code>repeated .binancetrade.Trade tradelist = 1;</code>
     */
    public java.util.List<Trade.Builder>
         getTradelistBuilderList() {
      return getTradelistFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
            Trade, Trade.Builder, TradeOrBuilder>
        getTradelistFieldBuilder() {
      if (tradelistBuilder_ == null) {
        tradelistBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
                Trade, Trade.Builder, TradeOrBuilder>(
                tradelist_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        tradelist_ = null;
      }
      return tradelistBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:binancetrade.Trade_List)
  }

  // @@protoc_insertion_point(class_scope:binancetrade.Trade_List)
  private static final Trade_List DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Trade_List();
  }

  public static Trade_List getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Trade_List>
      PARSER = new com.google.protobuf.AbstractParser<Trade_List>() {
    @java.lang.Override
    public Trade_List parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Trade_List(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Trade_List> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Trade_List> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Trade_List getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

