// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade.proto

package org.yourkoder.com.dataformat;

public interface Trade_ListOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binancetrade.Trade_List)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .binancetrade.Trade tradelist = 1;</code>
   */
  java.util.List<Trade>
      getTradelistList();
  /**
   * <code>repeated .binancetrade.Trade tradelist = 1;</code>
   */
  Trade getTradelist(int index);
  /**
   * <code>repeated .binancetrade.Trade tradelist = 1;</code>
   */
  int getTradelistCount();
  /**
   * <code>repeated .binancetrade.Trade tradelist = 1;</code>
   */
  java.util.List<? extends TradeOrBuilder>
      getTradelistOrBuilderList();
  /**
   * <code>repeated .binancetrade.Trade tradelist = 1;</code>
   */
  TradeOrBuilder getTradelistOrBuilder(
      int index);
}
