// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: trade.proto

package org.yourkoder.com.dataformat;

public interface TradeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:binancetrade.Trade)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 id = 1;</code>
   * @return The id.
   */
  long getId();

  /**
   * <code>string symbol = 2;</code>
   * @return The symbol.
   */
  java.lang.String getSymbol();
  /**
   * <code>string symbol = 2;</code>
   * @return The bytes for symbol.
   */
  com.google.protobuf.ByteString
      getSymbolBytes();

  /**
   * <code>string time = 3;</code>
   * @return The time.
   */
  java.lang.String getTime();
  /**
   * <code>string time = 3;</code>
   * @return The bytes for time.
   */
  com.google.protobuf.ByteString
      getTimeBytes();

  /**
   * <code>sfixed64 timeStamp = 4;</code>
   * @return The timeStamp.
   */
  long getTimeStamp();

  /**
   * <code>double price = 5;</code>
   * @return The price.
   */
  double getPrice();
}
